first commit

diff --git a/.github/workflows/build5.yml b/.github/workflows/build5.yml
--- a/.github/workflows/build5.yml
+++ b/.github/workflows/build5.yml
@@ -1,23 +1,28 @@
-name: Build External Project
+name: Build tiny_computer
 
 on:
   workflow_dispatch:
 
 jobs:
-  build-external-project:
+  build-tiny-computer:
     runs-on: ubuntu-latest
     steps:
-    - name: Checkout external repository
+    - name: Checkout tiny_computer repository
       uses: actions/checkout@v2
       with:
-        repository: 'https://github.com/Cateners/tiny_computer'  
-        path: external-project  # 可选：指定一个子目录来检出项目
+        repository: 'Cateners/tiny_computer'
+        submodules: 'recursive'  # 确保子模块也被检出
 
     - name: Set up Java
       uses: actions/setup-java@v3
       with:
         java-version: '18'
         distribution: 'temurin'
+        check-latest: false
+        server-id: github
+        server-username: GITHUB_ACTOR
+        server-password: GITHUB_TOKEN
+        overwrite-settings: true
 
     - name: Set up Android SDK
       uses: android-actions/setup-android@v3
@@ -26,21 +31,26 @@ jobs:
       uses: subosito/flutter-action@v2
       with:
         channel: stable
-        flutter-version: '3.3.0'  # 确保使用正确的 Flutter 版本
+        flutter-version: '3.24.0'
 
     - name: Install dependencies
       run: |
-        cd external-project  # 如果你在上一步中指定了子目录
         flutter pub get
+        # 确保所有依赖项都已安装，包括子模块
+
+    - name: Prepare build environment
+      run: |
+        wget --tries=3 https://github.com/Cateners/tiny_computer/releases/download/v1.0.18/debian-xfce.tar.xz || (echo "Failed to download debian-xfce.tar.xz" && exit 1)
+        mkdir -p assets
+        split -b 98M debian-xfce.tar.xz assets/debian.tar.xz.
 
     - name: Build APK
       run: |
-        cd external-project  # 如果你在上一步中指定了子目录
         flutter clean
-        flutter build apk --target-platform android-arm64
+        flutter build apk --target-platform android-arm64 --split-per-abi --obfuscate --split-debug-info=tiny_computer/sdi
 
     - name: Upload APK as artifact
       uses: actions/upload-artifact@v3
       with:
-        name: example-project-apk
-        path: external-project/build/app/outputs/flutter-apk/app-arm64-release.apk
+        name: tiny-computer-apk
+        path: build/app/outputs/flutter-apk/app-arm64-release.apk
